'''
@Author: Abdelaziz Neamatallah
@Date: 17.12.25
@Description: The main goal of this task is to implement a GAN-based anomaly detection system for ICS network traffic:
    - The objective is to classify network traffic samples as: 
        - Normal traffic
        - Anomalous traffic (attacks)
    - We should work on raw packet bytes directly.

    - Input representation:
        - The GAN must operate on raw network packets, represented as a matrix of size:
            - size = m * n
            - m = number of packets in the dataset
            - n = M = number of bytes extracted per packet.
            - M should be a parameter that is read from the command line. 
            - Bytes are taken directly from packets. 
            - Data can be:
                - Full packets
                - Reverse-engineered packet parts (will be used later in Task3). 
    - GAN Architecture overview:
        - It must be a Generative Adversarial Network (GAN) consisting of:
            - Discriminator (D)
                - Acts as anomaly detector / classifier.
            - Generator (G)
                - Creates fake packet data that should resemble real network packets. 
            - These two networks are trained adversarially:
                - The D learns to distinguish real vs fake. 
                - The G learns to fool the D. 
    - D Design: 
        - The discriminator must be a deep CNN with the following structure: 
            - Convolutional Part: 
                - 9 convolutional layers.
                - ReLU activation in all layers
                - Dropout after every convolutional layer exept: 
                    - The first layer
                    - The last layer
            - Fully Connected Part:
                - output of the final convolutional layer is flattened
                - Followed by 4 fully connected layers.
                - ReLU activation in all layers except the last layer.
            - Output: 
                - A single scalar value in range [0,1).
                - Represents how *real* the input sample is 
                - User for:
                    - GAN training. 
                    - Anomaly detection (option 1). 
    - G Design:
        - The generator must function as reverse CNN that transforms noise into packet-like data.
        - Input:
            - Random noise vector
            - Noise distribution is our choice. 
        - Fully Connected Layers: 
            - 4 fully connected layers
            - LeakyReLU activation. 
        - Convolutional Layers:
            - 8 convolutional layers with LeakyReLU 
            - First 4 convolutional layers must be preceded by upsampling
        - Output: 
            - Generated packets bytes matching the same shape as real input.
            - Output should resemble real packet byte distributions.
    - Custom Generator Loss
        - We should not use a standard GAN loss alone
        - Instead: 
            - Implement a custom loss function for the generator
            - The loss is computed using the input to the first fully connected layer of the discriminator. 
        - What this means:
            - We extract intermediate feature representations from the D.
            - Compute the difference between:
                - Features of real packets.
                - Features of generated packets.
        - Purpose: 
            - Forces the generator to match semantic packet features, not just byte-level similarity
            - Improves anomaly detection robustness.
        - This is called feature-matching loss. 
    - Anomaly Detection modes (Runtime choice):
        - After training, our system should support two anomaly detection strategies, selectable via command line:
            - Mode1:
                - Use D directly
                - Low realism score -> Anomalous
                - Fast and simple:
            - Mode2: 
                - Use genertor behavior to detect anomalies
                - Example: 
                    - Reconstruction error 
                    - Feature mismatch
                - More computationally expensive, but sometimes more robust. 
    - Hyperparameter Tuning: 
        - We must implement hyperparameter tuning for GAN
        - Example on tunable parameters:
            - Learning rate
            - Number of epochs
            - Kernel size
            - Number of filters
            - Dropout rates
        - This can be done via:
            - Grid search
            - Manual tuning
            - Automated tuning
        - The main goal is to show experimental rigor. 
    - How task2 is used in Task3:
        - In Task3, our GAN will be evaluated in Scenario 1 with:
            - Full packets or reverse-engineered packet chunks.
            - Physical reading sizes p = {5,10,15}. 
            - Raw bytes only (no autoencoder features).
        - We must report: 
            - Percision
            - Recall
            - Comparative plots
            - Clear experimental conclusions.
        - The GAN is evaluated twice:
            - Using D
            - Using G
'''